name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.6

      - name: Instalar dependências
        run: go mod tidy

      - name: Build do projeto
        run: go build ./...

      - name: Executar testes com cobertura
        run: go test -cover -coverpkg=./api/... -coverprofile=coverage.out ./api -v

      - name: Exibir cobertura de código no log
        run: go tool cover -func=coverage.out

      - name: Gerar relatório de cobertura HTML
        run: go tool cover -html=coverage.out -o coverage.html

      - name: Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.html
          retention-days: 5
